### ISSUE TITLE
questions about analagous example

### ISSUE THREAD

**Issue by fido20160817** [RyannDaGreat/peekaboo#1]
Hi, I have read your paper. In Sec. 5 Analagous Example, it is described that "we use implicit neural functions to represent each of these elements, with one network for background and a shared network for foreground and alpha mask." Do you mean you use **an implicit neural function** to generate the foreground, and **another shared implicit neural function** to generate the foreground and alpha mask? (if the implicit neural function is leveraged to generate foreground and background, what's the corresponding input?) Am I right? (So the diffusion model is not used to generate images but as just a similarity measure.)

Further, there seems a wrong description in your paper:

![8AGwQpD5h7](https://user-images.githubusercontent.com/21076140/231934563-eecccc72-a191-4723-ab1e-d74bccf3f025.png)

as marked in red: composite image and alpha mask are represented by the same variable...

**Comment by RyannDaGreat** [comment]
Hi there! This Github repo is probably not the most sensible place to discuss the paper itself, since the latex files aren't in this repo (this repo contains the code, not the paper). My email is rburgert@cs.stonybrook.edu by the way. That being said, you're right - that is a mistake in the paper, thank you for pointing that out :) We'll be uploading a new version of the paper to Arxiv soon. 

To answer your question...I'm not quite sure I understand what you're asking but I'll try my best. We can schedule a call if you're still confused! In the analagous example, there are several RGB background images, and several RGBA foreground images (please remember that RGBA means Red Green Blue Alpha, where alpha is transparency). Each image is represented with it's own implicit neural function (aka fourier feature network; an MLP that takes in X and Y and outputs RGB or RGBA). Yes, the diffusion model is just used a similarly measure, just as CLIP could be. The difference is that CLIP isn't good enough to generate good imagery, whereas dream loss is. Fourier feature networks: https://bmild.github.io/fourfeat/ it shows the inputs in the example! It takes in X,Y (a 2d vector) and returns RGBA (a 4-valued vector) and does this for every pixel in the image. I hope this helps? Did I answer your question?

**Comment by fido20160817** [comment]
Hi, it's better for me to understand now, and I would refer to Fourier feature networks: https://bmild.github.io/fourfeat/ to see more. Thanks for your response. I will email you if I have more questions. Thanks again, and very nice work!
